export const CATEGORY_SELECT = 'CATEGORY_SELECT';
export const TODO_DONE_TOGGLE = 'TODO_DONE_TOGGLE';
export const TODO_SAVE = 'TODO_SAVE';

export const TODO_REMOVE = 'TODO_REMOVE';
export const TODO_DELETE = 'TODO_DELETE';

export const TASK_DELETE_CONFIRM = 'TASK_DELETE_CONFIRM';
export const TASK_DELETE_REJECT = 'TASK_DELETE_REJECT';

export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD_CHANGE = 'CATEGORY_ADD_CHANGE';

export const TASK_ADD = 'TASK_ADD';
export const TASK_ADD_NAME_CHANGE = 'TASK_ADD_NAME_CHANGE';
export const TASK_ADD_DESC_CHANGE = 'TASK_ADD_DESC_CHANGE';

export const MODAL_SHOW = 'app/modals/MODAL_SHOW';

